apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/lcarva-hacbs/golden-container-stage?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: golden-container-stage
    appstudio.openshift.io/component: golden-container-stage
    pipelines.appstudio.openshift.io/type: build
  name: golden-container-stage-on-push
  namespace: lucarval-tenant
spec:
  params:
  - name: dockerfile
    value: Containerfile
  - name: git-url
    value: '{{source_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/lucarval-tenant/golden-container-stage/golden-container-stage:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/lucarval/pipeline-docker-build:2024-04-18-141354@sha256:203cb2d5c91e0e8af0ed3c5815c3ab33e1d17a912190a6ebf99327ad78c92ca2
      - name: name
        value: docker-build
      - name: kind
        value: pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
